(()=>{const $=id=>document.getElementById(id);const map=L.map("gameMap",{zoomControl:true}).setView([48.414,-89.245],15);L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{maxZoom:20,attribution:"© OpenStreetMap © CARTO"}).addTo(map);
const icon=(c,h,s=28)=>L.divIcon({className:"",html:`<div class="${c}">${h}</div>`,iconSize:[s,s],iconAnchor:[s/2,s/2]});const st=document.createElement("style");st.textContent=".survivor{width:32px;height:32px;border-radius:50%;background:#59ff87;border:3px solid #e2ffea;box-shadow:0 0 0 9px #59ff8720,0 0 22px #59ff87;display:grid;place-items:center;color:#06240e}.zombie{width:18px;height:18px;border-radius:50%;background:#ff4f61;border:2px solid #ffd2d6;box-shadow:0 0 13px #ff4f61}.poi{padding:5px 7px;background:#111d;border:1px solid #4e5553;border-radius:4px;color:#d5d9d7;font:800 8px monospace;white-space:nowrap}.destination{width:18px;height:18px;border-radius:50%;border:2px solid #fff;background:#59ff87;box-shadow:0 0 18px #59ff87}";document.head.appendChild(st);
let player=[48.414,-89.245],moving=false,selected=false,health=100,hunger=82,thirst=76,stamina=94,minutes=480;
const survivor=L.marker(player,{icon:icon("survivor","▲",32),zIndexOffset:1000}).addTo(map);let destMarker,routeLine;
const buildings=[[[48.4154,-89.2488],[48.4154,-89.2460],[48.4139,-89.2460],[48.4139,-89.2488]],[[48.4130,-89.2445],[48.4130,-89.2423],[48.4117,-89.2423],[48.4117,-89.2445]],[[48.4168,-89.2430],[48.4168,-89.2410],[48.4158,-89.2410],[48.4158,-89.2430]]];buildings.forEach(p=>L.polygon(p,{color:"#303735",weight:1,fillColor:"#1a211f",fillOpacity:.9,interactive:false}).addTo(map));L.polyline([[48.421,-89.258],[48.418,-89.254],[48.414,-89.253],[48.410,-89.255],[48.406,-89.251]],{color:"#263f52",weight:18,opacity:.85,interactive:false}).addTo(map);
const pois=[{name:"INTERCITY COMMERCIAL ZONE",pos:[48.4148,-89.2468]},{name:"PARKING AREA",pos:[48.4125,-89.245]},{name:"RESIDENTIAL BLOCK",pos:[48.417,-89.2415]},{name:"UNKNOWN STRUCTURE",pos:[48.4108,-89.2405]}],found=new Set();pois.forEach(p=>p.marker=L.marker(p.pos,{icon:icon("poi","?",70)}).addTo(map));
function log(m){let e=document.createElement("div");e.className="log";e.innerHTML=`<b>[${$("gameTime").textContent}]</b> ${m}`;$("gameFeed").prepend(e);while($("gameFeed").children.length>7)$("gameFeed").lastElementChild.remove()}
function hud(){[["health",health],["hunger",hunger],["thirst",thirst],["stamina",stamina]].forEach(([k,v])=>{$(k).textContent=Math.round(v)+"%";$(k+"Bar").style.width=v+"%"});let h=Math.floor(minutes/60)%24,m=minutes%60;$("gameTime").textContent=String(h).padStart(2,"0")+":"+String(m).padStart(2,"0");survivor.getElement()?.classList.toggle("survivor-selected",selected)}
function blocked(p){return buildings.some(poly=>{let a=poly.map(x=>x[0]),b=poly.map(x=>x[1]);return p.lat>Math.min(...a)&&p.lat<Math.max(...a)&&p.lng>Math.min(...b)&&p.lng<Math.max(...b)})}
function route(dest){let s=L.latLng(player),e=L.latLng(dest),pts=[s];buildings.forEach(poly=>{let box=L.latLngBounds(poly),line=L.latLngBounds(s,e);if(box.intersects(line)){let pad=.0004,c=[[box.getNorth()+pad,box.getWest()-pad],[box.getNorth()+pad,box.getEast()+pad],[box.getSouth()-pad,box.getWest()-pad],[box.getSouth()-pad,box.getEast()+pad]].map(x=>L.latLng(x[0],x[1]));c.sort((x,y)=>x.distanceTo(s)+x.distanceTo(e)-y.distanceTo(s)-y.distanceTo(e));pts.push(c[0])}});pts.push(e);return pts}
function discover(){pois.forEach(p=>{if(!found.has(p.name)&&L.latLng(player).distanceTo(p.pos)<260){found.add(p.name);p.marker.setIcon(icon("poi","⌂",70));p.marker.bindPopup("<b>"+p.name+"</b><br><small>LOCATION DISCOVERED</small>");log("NEW LOCATION DISCOVERED • "+p.name);$("objective").textContent="EXPLORE • DISCOVER • FIND SUPPLIES"}})}
function move(pts){moving=true;selected=false;let i=0;function next(){if(i>=pts.length-1){moving=false;log("ARRIVED AT DESTINATION");discover();hud();return}let a=L.latLng(player),b=pts[++i],n=0,steps=Math.max(15,Math.ceil(a.distanceTo(b)/4)),t=setInterval(()=>{n++;let x=n/steps;player=[a.lat+(b.lat-a.lat)*x,a.lng+(b.lng-a.lng)*x];survivor.setLatLng(player);minutes++;stamina=Math.max(0,stamina-.04);discover();hud();if(n>=steps){clearInterval(t);next()}},40)}next()}
survivor.on("click",e=>{L.DomEvent.stopPropagation(e);if(moving)return;selected=!selected;log(selected?"SURVIVOR SELECTED • CLICK DESTINATION":"MOVEMENT CANCELLED");$("objective").textContent=selected?"CLICK MAP TO SET DESTINATION":"FIND SUPPLIES • SURVIVE THE DAY";hud()});
map.on("click",e=>{if(!selected||moving)return;if(blocked(e.latlng)){log("BLOCKED • CANNOT WALK THROUGH BUILDING");return}let pts=route(e.latlng);if(destMarker)map.removeLayer(destMarker);if(routeLine)map.removeLayer(routeLine);destMarker=L.marker(e.latlng,{icon:icon("destination","",18)}).addTo(map);routeLine=L.polyline(pts,{color:"#59ff87",weight:3,dashArray:"7 8",opacity:.85}).addTo(map);let d=pts.reduce((a,p,i)=>i?a+L.latLng(pts[i-1]).distanceTo(p):0,0);log("ROUTE CALCULATED • "+Math.round(d)+"M");$("objective").textContent="MOVING • "+Math.round(d)+"M ROUTE";setTimeout(()=>move(pts),350)});
$("scavengeBtn").onclick=()=>log("DISCOVER A BUILDING FIRST • MOVE INTO INTERACTION RANGE");$("restBtn").onclick=()=>{if(!moving){stamina=Math.min(100,stamina+20);minutes+=45;log("RESTED • STAMINA RECOVERED");hud()}};$("newGameBtn").onclick=()=>location.reload();setInterval(()=>{if(!moving){hunger=Math.max(0,hunger-.05);thirst=Math.max(0,thirst-.08);minutes++;hud()}},3000);log("NAVIGATION ENGINE ONLINE");log("CLICK SURVIVOR TO BEGIN");discover();hud();setTimeout(()=>map.invalidateSize(),250)})();