(()=>{
const $=id=>document.getElementById(id);const map=L.map("gameMap",{zoomControl:true}).setView([48.410,-89.250],13);
L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{maxZoom:20,attribution:"© OpenStreetMap © CARTO"}).addTo(map);
const icon=(cls,html,size=28)=>L.divIcon({className:"",html:`<div class="${cls}">${html}</div>`,iconSize:[size,size],iconAnchor:[size/2,size/2]});
const css=document.createElement("style");css.textContent=`.survivor{width:30px;height:30px;border-radius:50%;background:#59ff87;border:3px solid #d8ffe3;box-shadow:0 0 0 8px #59ff8720,0 0 20px #59ff87;display:grid;place-items:center;color:#06240e;font-size:14px}.zombie{width:18px;height:18px;border-radius:50%;background:#ff4f61;border:2px solid #ffd2d6;box-shadow:0 0 13px #ff4f61;display:grid;place-items:center;font-size:9px}.loot{width:22px;height:22px;border-radius:5px;background:#ffc96b;color:#241a06;border:2px solid #ffe4a8;display:grid;place-items:center;font-size:11px}`;document.head.appendChild(css);
let player=[48.414,-89.245],moving=false,health=100,hunger=82,thirst=76,stamina=94,minutes=480,inventory=[];
const survivor=L.marker(player,{icon:icon("survivor","▲",30),zIndexOffset:1000}).addTo(map).bindPopup("ALPHA-01 • SURVIVOR");
const lootSites=[
{name:"RESIDENTIAL HOUSE",pos:[48.417,-89.252],tier:"COMMON",items:["Water","Food"]},{name:"CORNER STORE",pos:[48.410,-89.240],tier:"UNCOMMON",items:["Food","Food","Bandage"]},{name:"PHARMACY",pos:[48.405,-89.247],tier:"RARE",items:["Medkit","Bandage"]},{name:"WAREHOUSE",pos:[48.399,-89.258],tier:"UNCOMMON",items:["Tool","Water"]},{name:"GROCERY",pos:[48.421,-89.236],tier:"RARE",items:["Food","Food","Water"]}];
lootSites.forEach(s=>L.marker(s.pos,{icon:icon("loot","▣",22)}).addTo(map).bindPopup(`<b>${s.name}</b><br>${s.tier} LOOT<br><button class="site-loot" data-site="${s.name}">SCAVENGE</button>`));
const zombies=[];for(let i=0;i<28;i++){const p=[48.39+Math.random()*.055,-89.285+Math.random()*.075];zombies.push({p,marker:L.marker(p,{icon:icon("zombie","●",18)}).addTo(map)})}
function log(msg){const e=document.createElement("div");e.className="log";e.innerHTML=`<b>[DAY 01]</b> ${msg}`;$("gameFeed").prepend(e);while($("gameFeed").children.length>7)$("gameFeed").lastElementChild.remove()}
function updateHUD(){[["health",health],["hunger",hunger],["thirst",thirst],["stamina",stamina]].forEach(([k,v])=>{$(k).textContent=Math.round(v)+"%";$(k+"Bar").style.width=Math.max(0,v)+"%"});$("inventoryCount").textContent=`${inventory.length} / 8`;$("inventory").innerHTML=inventory.length?inventory.map(x=>`<span class="item">${x}</span>`).join(""):"<span>EMPTY</span>";const h=Math.floor(minutes/60)%24,m=minutes%60;$("gameTime").textContent=`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`;$("threat").textContent=`THREAT: ${zombies.length>25?"MODERATE":"LOW"}`}
function moveTo(dest){if(moving)return;moving=true;const start=player.slice(),steps=90;let n=0;log("MOVE ORDER CONFIRMED");const timer=setInterval(()=>{n++;const t=n/steps;player=[start[0]+(dest.lat-start[0])*t,start[1]+(dest.lng-start[1])*t];survivor.setLatLng(player);stamina=Math.max(0,stamina-.08);hunger=Math.max(0,hunger-.015);thirst=Math.max(0,thirst-.025);minutes++;if(n>=steps){clearInterval(timer);moving=false;log("ARRIVED AT DESTINATION");checkThreat();}updateHUD()},35)}
function nearSite(){return lootSites.find(s=>L.latLng(player).distanceTo(s.pos)<180)}
function scavenge(){const s=nearSite();if(!s){log("NO LOOT SITE IN RANGE");return}if(inventory.length>=8){log("INVENTORY FULL");return}const item=s.items[Math.floor(Math.random()*s.items.length)];inventory.push(item);minutes+=18;hunger=Math.max(0,hunger-2);thirst=Math.max(0,thirst-3);$("objective").textContent=`LOOTED: ${item.toUpperCase()} • CONTINUE SURVIVING`;log(`SCAVENGED ${s.name} • FOUND ${item}`);updateHUD();checkThreat(true)}
function checkThreat(force=false){const close=zombies.filter(z=>L.latLng(player).distanceTo(z.p)<force?700:420);if(close.length>=3||force&&Math.random()<.35){$("eventTitle").textContent="INFECTED DETECTED";$("eventText").textContent=`${Math.max(3,close.length)} infected signatures are moving in the district. Choose your response.`;$("eventModal").classList.remove("hidden");log("THREAT EVENT • INFECTED NEARBY")}}
map.on("click",e=>moveTo(e.latlng));$("scavengeBtn").onclick=scavenge;$("restBtn").onclick=()=>{if(moving)return;stamina=Math.min(100,stamina+22);hunger=Math.max(0,hunger-4);thirst=Math.max(0,thirst-5);minutes+=45;log("RESTED • STAMINA RECOVERED");updateHUD()};$("newGameBtn").onclick=()=>location.reload();document.querySelectorAll(".modal-actions button").forEach(b=>b.onclick=()=>{$("eventModal").classList.add("hidden");if(b.dataset.action==="run"){stamina=Math.max(0,stamina-15);minutes+=8;log("ESCAPED INFECTED CONTACT");}else log("HID UNTIL THE THREAT PASSED");updateHUD()});setInterval(()=>{if(!moving){hunger=Math.max(0,hunger-.05);thirst=Math.max(0,thirst-.08);minutes++;updateHUD()}},3000);log("OUTBREAK PROTOCOL INITIALIZED");log("ALPHA-01 ACTIVE • FIND SUPPLIES");updateHUD();setTimeout(()=>map.invalidateSize(),250);
})();