(()=>{"use strict";const $=s=>document.querySelector(s);
const ZONES=[
{id:"hospital",icon:"🏥",name:"ST. JOSEPH'S MEDICAL COMPLEX",risk:"SEVERE",bonus:"MEDICAL CACHE",desc:"Medical supplies and trauma equipment. Dense infected presence.",loot:["💉 Medical Kit","🩸 Trauma Kit","💊 Painkillers","🩹 Bandage"],infected:5},
{id:"police",icon:"🚔",name:"NORTH POLICE STATION",risk:"HIGH",bonus:"LOCKERS + KEYCARDS",desc:"Secured lockers, tactical equipment and restricted access items.",loot:["🔐 Police Locker","🗝️ Master Keycard","🔧 Crowbar","🩹 Bandage"],infected:4},
{id:"gunstore",icon:"🔫",name:"FRONTIER SPORTING GOODS",risk:"CRITICAL",bonus:"WEAPON CACHE",desc:"High-value weapons attract the most desperate survivors and infected.",loot:["🪓 Rescue Axe","🔫 Service Pistol","🔦 Flashlight","🔧 Crowbar"],infected:6},
{id:"industrial",icon:"🏭",name:"INTERCITY INDUSTRIAL YARD",risk:"MODERATE",bonus:"TECH + TOOLS",desc:"Power infrastructure, repair equipment and industrial salvage.",loot:["🔋 Power Cell","🧰 Repair Kit","🔧 Crowbar","📡 Emergency Beacon"],infected:3},
{id:"residential",icon:"🏘️",name:"WESTFORT RESIDENTIAL BLOCK",risk:"LOW",bonus:"HOUSEHOLD SUPPLIES",desc:"Lower threat density. Common survival supplies and civilian caches.",loot:["🥫 Canned Food","💧 Water Bottle","🩹 Bandage","🔦 Flashlight"],infected:2}
];
let visited={};
function load(){try{visited=JSON.parse(localStorage.getItem("outbreak_high_value_zones")||"{}")}catch{visited={}}}
function save(){localStorage.setItem("outbreak_high_value_zones",JSON.stringify(visited))}
function open(){const m=modal();$("#zoneResults").innerHTML=ZONES.map(z=>'<button class="zone-row '+z.risk.toLowerCase()+'" data-zone="'+z.id+'"><span class="zone-icon">'+z.icon+'</span><div><small>THREAT: '+z.risk+'</small><b>'+z.name+'</b><em>'+z.bonus+'</em></div><strong>'+z.infected+' ☣</strong></button>').join("");m.classList.remove("hidden");document.querySelectorAll("[data-zone]").forEach(b=>b.onclick=()=>inspect(b.dataset.zone))}
function inspect(id){const z=ZONES.find(x=>x.id===id);const done=visited[id];$("#zoneResults").innerHTML='<section class="zone-detail"><div class="zone-hero-icon">'+z.icon+'</div><span class="zone-risk '+z.risk.toLowerCase()+'">THREAT: '+z.risk+'</span><h3>'+z.name+'</h3><b class="zone-bonus">'+z.bonus+'</b><p>'+z.desc+'</p><div class="zone-intel"><span>EXPECTED INFECTED</span><strong>'+z.infected+' CONTACTS</strong><span>PRIORITY LOOT</span><strong>'+z.loot.slice(0,3).join(" • ")+'</strong></div><div class="modal-actions"><button id="zoneBack">BACK</button><button id="zoneSearch" '+(done?"disabled":"")+'> '+(done?"AREA ALREADY CLEARED":"ENTER HIGH-VALUE ZONE")+'</button></div></section>';$("#zoneBack").onclick=open;$("#zoneSearch").onclick=()=>raidZone(z)}
function raidZone(z){const inv=getInv(),cap=Number(localStorage.getItem("outbreak_inventory_capacity")||8),space=Math.max(0,cap-inv.length),count=z.risk==="CRITICAL"?3:z.risk==="SEVERE"?3:2;const found=[];for(let i=0;i<count;i++)found.push(z.loot[Math.floor(Math.random()*z.loot.length)]);const taken=found.slice(0,space);localStorage.setItem("outbreak_inventory",JSON.stringify([...inv,...taken]));visited[z.id]={cleared:true,time:Date.now()};save();$("#zoneResults").innerHTML='<section class="zone-detail zone-complete"><span class="modal-kicker">ZONE SEARCH COMPLETE</span><h3>'+z.name+'</h3><div class="zone-loot">'+found.map((x,i)=>'<div class="'+(i>=space?"blocked":"")+'">'+x+'<small>'+ (i<space?"SECURED":"NO SPACE")+'</small></div>').join("")+'</div><div class="zone-consequence">☣ '+z.infected+' INFECTED CONTACTS REPORTED DURING OPERATION</div><button id="zoneDone" class="game-btn">RETURN TO RAID</button></section>';$("#zoneDone").onclick=()=>{$("#highValueZoneModal").classList.add("hidden");update();log("High-value zone cleared: "+z.name+" • "+taken.length+" assets secured")}}
function getInv(){try{return JSON.parse(localStorage.getItem("outbreak_inventory")||"[]")}catch{return[]}}
function update(){const n=$("#inventoryCount"),i=getInv(),c=localStorage.getItem("outbreak_inventory_capacity")||8;if(n)n.textContent=i.length+" / "+c}
function log(t){const f=$("#gameFeed");if(f){const d=document.createElement("div");d.className="feed-item";d.textContent=t;f.prepend(d)}}
function modal(){let m=$("#highValueZoneModal");if(!m){m=document.createElement("div");m.id="highValueZoneModal";m.className="modal hidden";m.innerHTML='<div class="modal-card zone-modal"><span class="modal-kicker">PHASE 6C // AREA INTELLIGENCE</span><h2>HIGH-VALUE ZONES</h2><div id="zoneResults"></div><div class="modal-actions"><button id="zoneClose">CLOSE</button></div></div>';document.body.appendChild(m);$("#zoneClose").onclick=()=>m.classList.add("hidden")}return m}
function init(){load();const host=$(".game-actions");if(host){const b=document.createElement("button");b.id="zonesBtn";b.className="game-btn danger";b.textContent="◈ HIGH-VALUE ZONES";host.insertBefore(b,host.firstChild);b.onclick=open}document.addEventListener("keydown",e=>{if(e.key.toLowerCase()==="z"&&!e.repeat)open()})}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init()})();