(()=>{"use strict";const $=s=>document.querySelector(s);
const DEFAULT={established:false,level:1,name:"NORTHERN HAVEN",resources:{food:12,medical:4,materials:8},morale:65,defense:10,facilities:{shelter:1,storage:0,medical:0,workshop:0,watchtower:0},history:[]};
function load(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem("cheegunFOB")||"{}")}}catch{return structuredClone(DEFAULT)}}
function save(s){localStorage.setItem("cheegunFOB",JSON.stringify(s));render();document.dispatchEvent(new CustomEvent("cheegunFOBUpdated",{detail:s}))}
function network(){try{return JSON.parse(localStorage.getItem("cheegunSurvivorNetwork")||'{"survivors":[],"reputation":0}')}catch{return{survivors:[],reputation:0}}}
function state(){return load()}
function log(t){const f=$("#gameFeed");if(f){const d=document.createElement("div");d.className="feed-item";d.textContent=t;f.prepend(d)}}
const facilities={shelter:{name:"SURVIVOR SHELTER",cost:{materials:4},effect:"+ survivor capacity"},storage:{name:"STORAGE CACHE",cost:{materials:5},effect:"+ resource capacity"},medical:{name:"FIELD MEDICAL",cost:{materials:6,medical:2},effect:"+ recovery"},workshop:{name:"WORKSHOP",cost:{materials:8},effect:"crafting expansion"},watchtower:{name:"WATCHTOWER",cost:{materials:10},effect:"+10 defense"}};
function can(s,c){return Object.entries(c).every(([k,v])=>(s.resources[k]||0)>=v)}
function spend(s,c){Object.entries(c).forEach(([k,v])=>s.resources[k]-=v)}
function establish(){const s=state(),n=network();if(n.survivors.length<1){alert("FOB REQUIREMENT\n\nRescue at least one survivor before establishing a permanent base.");return}s.established=true;s.history.unshift({type:"ESTABLISHED",at:Date.now()});save(s);log("🏕 FOB ESTABLISHED • NORTHERN HAVEN BECOMES A SAFE POINT");}
function build(key){const s=state(),f=facilities[key];if(!s.established)return;if(!can(s,f.cost)){log("⚠ FOB CONSTRUCTION FAILED • INSUFFICIENT RESOURCES");return}spend(s,f.cost);s.facilities[key]=(s.facilities[key]||0)+1;if(key==="watchtower")s.defense+=10;s.history.unshift({type:"BUILT",name:f.name,at:Date.now()});save(s);log("🔧 FOB UPGRADE COMPLETE • "+f.name)}
function assign(name){const s=state(),n=network(),person=n.survivors.find(x=>x.name===name);if(!person)return;const roles=["SCAVENGER","MEDIC","GUARD","BUILDER","COORDINATOR"];person.role=roles[(roles.indexOf(person.role||"")+1)%roles.length]||roles[0];localStorage.setItem("cheegunSurvivorNetwork",JSON.stringify(n));s.history.unshift({type:"ASSIGNED",name,role:person.role,at:Date.now()});save(s)}
function modal(){let m=$("#fobModal");if(m)return m;m=document.createElement("div");m.id="fobModal";m.className="modal hidden";m.innerHTML='<div class="modal-card fob-modal"><span class="modal-kicker">PHASE 9A // FORWARD OPERATING BASE</span><h2 id="fobTitle">NORTHERN HAVEN</h2><div id="fobContent"></div><div class="modal-actions"><button id="fobClose">CLOSE</button></div></div>';document.body.appendChild(m);$("#fobClose").onclick=()=>m.classList.add("hidden");return m}
function open(){const s=state(),m=modal(),n=network();$("#fobTitle").textContent=s.name+" // LEVEL "+s.level;$("#fobContent").innerHTML=!s.established?'<div class="fob-empty">🏕<h3>ESTABLISH A FORWARD OPERATING BASE</h3><p>You cannot rebuild humanity alone. Rescue survivors, secure resources, then create a place worth defending.</p><button id="establishFOB" class="game-btn">ESTABLISH FOB</button></div>':'<div class="fob-grid"><section><label>POPULATION</label><b>'+n.survivors.length+'</b></section><section><label>MORALE</label><b>'+s.morale+'%</b></section><section><label>DEFENSE</label><b>'+s.defense+'</b></section></div><div class="fob-resources"><span>🥫 FOOD <b>'+s.resources.food+'</b></span><span>💉 MEDICAL <b>'+s.resources.medical+'</b></span><span>🔩 MATERIALS <b>'+s.resources.materials+'</b></span></div><h3>BUILD & EXPAND</h3><div class="fob-builds">'+Object.entries(facilities).map(([k,f])=>'<button data-build="'+k+'"><b>'+f.name+'</b><small>LVL '+(s.facilities[k]||0)+' • '+Object.entries(f.cost).map(([x,v])=>x.toUpperCase()+" "+v).join(" / ")+'</small><em>'+f.effect+'</em></button>').join("")+'</div><h3>SURVIVOR ROSTER</h3><div class="fob-roster">'+(n.survivors.length?n.survivors.map(x=>'<button data-survivor="'+x.name+'"><b>'+x.name+'</b><span>'+x.role+'</span></button>').join(""):"NO SURVIVORS AT BASE")+'</div>';m.classList.remove("hidden");$("#establishFOB")?.addEventListener("click",()=>{establish();open()});m.querySelectorAll("[data-build]").forEach(b=>b.onclick=()=>{build(b.dataset.build);open()});m.querySelectorAll("[data-survivor]").forEach(b=>b.onclick=()=>{assign(b.dataset.survivor);open()})}
function render(){const s=state(),n=network(),card=$("#fobStatus");if(!card)return;$("#fobPopulation").textContent=n.survivors.length;$("#fobDefense").textContent=s.defense;$("#fobLevel").textContent=s.established?"LVL "+s.level:"UNESTABLISHED";$("#fobSummary").textContent=s.established?s.name+" • "+n.survivors.length+" SURVIVORS":"RESCUE A SURVIVOR TO ESTABLISH"}
function panel(){if($("#fobStatus"))return;const hud=$(".hud"),c=document.createElement("section");c.id="fobStatus";c.className="hud-card fob-status";c.innerHTML='<div class="hud-label">FORWARD OPERATING BASE <span id="fobLevel">UNESTABLISHED</span></div><div class="fob-mini"><span>POP <b id="fobPopulation">0</b></span><span>DEF <b id="fobDefense">10</b></span></div><p id="fobSummary">RESCUE A SURVIVOR TO ESTABLISH</p><button id="openFOB" class="open-inventory">MANAGE FOB →</button></section>';hud.insertBefore(c,$(".feed-card")||null);$("#openFOB").onclick=open}
function hooks(){document.addEventListener("cheegunSurvivorRecruited",()=>{render();const s=state();if(!s.established)log("🏕 NEW POSSIBILITY • YOU CAN NOW ESTABLISH A FORWARD OPERATING BASE")});document.addEventListener("cheegunMissionStarted",()=>{const s=state();if(s.established){s.resources.food++;s.resources.materials++;save(s)}})}
function init(){panel();render();hooks();const host=$(".game-actions");if(host){const b=document.createElement("button");b.id="fobBtn";b.className="game-btn";b.textContent="🏕 FOB";host.insertBefore(b,host.firstChild);b.onclick=open}document.addEventListener("keydown",e=>{if(e.key.toLowerCase()==="b"&&!e.repeat)open()});log("FOB SYSTEM READY • RESCUE SURVIVORS • PRESS B TO MANAGE BASE")}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init()})();