(()=>{"use strict";
const MAPS=[
{id:"sioux-lookout",name:"SIOUX LOOKOUT",subtitle:"NORTHERN OUTPOST",difficulty:2,population:"LOW",infected:"LOW–MEDIUM",loot:"MEDIUM",horde:"SMALL",extract:"EASIER",modifier:"RESOURCE SCARCITY",description:"A smaller northern town. Fewer infected and smaller hordes, but limited supplies, long distances and fewer extraction options.",status:"AVAILABLE",recommended:true,href:"outbreak.html",icon:"🏘️"},
{id:"thunder-bay",name:"THUNDER BAY",subtitle:"URBAN OUTBREAK",difficulty:4,population:"HIGH",infected:"HIGH",loot:"HIGH",horde:"LARGE",extract:"DIFFICULT",modifier:"URBAN DENSITY",description:"Dense urban districts, high-value infrastructure and dangerous outbreak pressure.",status:"AVAILABLE",href:"outbreak.html",icon:"🏙️"},
{id:"remote",name:"REMOTE COMMUNITY",subtitle:"ISOLATION ZONE",difficulty:3,population:"LOW",infected:"UNKNOWN",loot:"LOW",horde:"MEDIUM",extract:"LIMITED",modifier:"ISOLATION",description:"Communities cut off from the outside world.",status:"LOCKED",icon:"🌲"},
{id:"metro",name:"MAJOR METRO",subtitle:"COLLAPSED CITY",difficulty:5,population:"EXTREME",infected:"EXTREME",loot:"VERY HIGH",horde:"OVERWHELMING",extract:"SEVERE",modifier:"MASS OUTBREAK",description:"Future endgame operation.",status:"LOCKED",icon:"🌆"}];
const $=s=>document.querySelector(s);
function stars(n){return "★".repeat(n)+"☆".repeat(5-n)}
function open(){const m=modal();render();m.classList.remove("hidden")}
function render(){const host=$("#mapSelectResults");host.innerHTML=MAPS.map(m=>'<button class="world-map-card '+(m.status==="LOCKED"?"locked":"")+(m.recommended?" recommended":"")+'" data-map="'+m.id+'" '+(m.status==="LOCKED"?"disabled":"")+ '><div class="map-card-icon">'+m.icon+'</div><div class="map-card-main"><span>'+m.subtitle+(m.recommended?" • RECOMMENDED START":"")+'</span><b>'+m.name+'</b><small>'+m.modifier+' • '+stars(m.difficulty)+'</small></div><em>'+m.status+'</em></button>').join("");document.querySelectorAll("[data-map]").forEach(b=>b.onclick=()=>inspect(b.dataset.map))}
function inspect(id){const m=MAPS.find(x=>x.id===id);$("#mapSelectResults").innerHTML='<section class="map-intel-detail"><div class="map-intel-icon">'+m.icon+'</div><span class="modal-kicker">WORLD INTELLIGENCE</span><h3>'+m.name+'</h3><div class="map-difficulty">'+stars(m.difficulty)+' <small>DIFFICULTY '+m.difficulty+'/5</small></div><p>'+m.description+'</p><div class="map-stat-grid"><span>POPULATION <b>'+m.population+'</b></span><span>INFECTED <b>'+m.infected+'</b></span><span>LOOT <b>'+m.loot+'</b></span><span>HORDE SIZE <b>'+m.horde+'</b></span><span>EXTRACTION <b>'+m.extract+'</b></span><span>PRIMARY CHALLENGE <b>'+m.modifier+'</b></span></div><div class="map-progression-note">'+(m.recommended?"START HERE • LEARN THE EXTRACTION LOOP WITH LOWER POPULATION DENSITY":"ADVANCED OPERATION • HIGHER RISK, HIGHER REWARD")+'</div><div class="modal-actions"><button id="mapBack">BACK</button><button id="deployMap">DEPLOY TO '+m.name+' →</button></div></section>';$("#mapBack").onclick=render;$("#deployMap").onclick=()=>deploy(m)}
function deploy(m){localStorage.setItem("cheegunSelectedMap",JSON.stringify(m));location.href=m.href}
function modal(){let m=$("#worldMapModal");if(!m){m=document.createElement("div");m.id="worldMapModal";m.className="modal hidden";m.innerHTML='<div class="modal-card world-map-modal"><span class="modal-kicker">PHASE 8A // OPERATION SELECT</span><h2>SELECT DEPLOYMENT REGION</h2><p class="world-map-intro">Population density changes the outbreak. Choose where you enter the collapse.</p><div id="mapSelectResults"></div><div class="modal-actions"><button id="mapSelectClose">CLOSE</button></div></div>';document.body.appendChild(m);$("#mapSelectClose").onclick=()=>m.classList.add("hidden")}return m}
function init(){const host=$(".game-actions");if(host){const b=document.createElement("button");b.id="worldMapBtn";b.className="game-btn";b.textContent="◉ DEPLOYMENT MAP";host.insertBefore(b,host.firstChild);b.onclick=open}document.addEventListener("keydown",e=>{if(e.key.toLowerCase()==="m"&&!e.repeat)open()});const selected=JSON.parse(localStorage.getItem("cheegunSelectedMap")||"null");if(selected&&$("#gameMap")){$(".title span").textContent=selected.name;const tip=$(".map-tip");if(tip)tip.textContent="OPERATION: "+selected.name+" • "+selected.modifier+" • SPACE = COMBAT"}}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init()})();