(()=>{"use strict";const $=s=>document.querySelector(s);
const WEAPONS={"kitchen-knife":{name:"KITCHEN KNIFE",damage:18,range:"MELEE",cooldown:900,noise:1},"rescue-axe":{name:"RESCUE AXE",damage:34,range:"MELEE",cooldown:1150,noise:2},"field-machete":{name:"FIELD MACHETE",damage:28,range:"MELEE",cooldown:700,noise:2},"service-pistol":{name:"SERVICE PISTOL",damage:46,range:"RANGED",cooldown:1250,noise:8}};
const ARMOR={"light-armor":.28};let lastAttack=0,contacts=[];
function loadout(){try{return JSON.parse(localStorage.getItem("cheegunActiveLoadout")||"null")}catch{return null}}
function getWeapon(){const l=loadout();return WEAPONS[l?.weapon]||WEAPONS["kitchen-knife"]}function armor(){const l=loadout();return ARMOR[l?.armor]||0}
function ensure(){if(!contacts.length)contacts=[{id:"infected-1",name:"INFECTED",hp:70,max:70,damage:14},{id:"infected-2",name:"INFECTED",hp:95,max:95,damage:18},{id:"infected-3",name:"INFECTED",hp:120,max:120,damage:22}]}
function combat(){const w=getWeapon(),now=Date.now();if(now-lastAttack<w.cooldown){flash("WEAPON RECOVERING");return}lastAttack=now;ensure();const alive=contacts.filter(x=>x.hp>0);if(!alive){flash("AREA CLEAR");return}const t=alive[Math.floor(Math.random()*alive.length)],crit=Math.random()<.16,dmg=Math.round(w.damage*(crit?1.6:1));t.hp=Math.max(0,t.hp-dmg);noise(w.noise);if(t.hp<=0){log("☣ CONTACT ELIMINATED • "+w.name);flash("CONTACT DOWN");}else{log("⚔ "+w.name+" • "+dmg+" DAMAGE"+(crit?" • CRITICAL":""));setTimeout(()=>counter(t),300)}render();updateObjective()}
function counter(t){if(t.hp<=0)return;const raw=t.damage,blocked=Math.round(raw*armor()),damage=Math.max(1,raw-blocked);let hp=Number(localStorage.getItem("outbreak_combat_health")||100);hp=Math.max(0,hp-damage);localStorage.setItem("outbreak_combat_health",hp);const e=$("#health"),bar=$("#healthBar");if(e)e.textContent=hp+"%";if(bar)bar.style.width=hp+"%";log("☣ INFECTED STRIKE • "+damage+" DAMAGE"+(blocked?" • ARMOR BLOCKED "+blocked:""));document.dispatchEvent(new CustomEvent("cheegunInfectedStrike",{detail:{target:t,damage}}));if(hp<=0){flash("OPERATOR DOWN");$("#attackBtn").disabled=true}}
function noise(n){if(n>=6){$("#threat").textContent="THREAT: ESCALATING";log("📢 WEAPON NOISE DETECTED • INFECTED ATTRACTED")}}
function render(){const host=$("#combatStatus");if(!host)return;const w=getWeapon(),alive=contacts.filter(x=>x.hp>0),target=alive[0];host.innerHTML='<b>'+w.name+'</b> • '+w.damage+' DMG • '+w.range+'<br><small>'+alive.length+' HOSTILES '+(target?"• TARGET "+target.hp+"/"+target.max+" HP":"• AREA CLEAR")+'</small>';const btn=$("#attackBtn");if(btn)btn.textContent=alive.length?"⚔ ATTACK • "+w.damage+" DMG":"✓ AREA CLEAR"}
function updateObjective(){const alive=contacts.filter(x=>x.hp>0).length;const o=$("#objective");if(o&&contacts.length)o.textContent=alive?"ELIMINATE "+alive+" HOSTILE CONTACT"+(alive>1?"S":"")+" • THEN CONTINUE":"AREA SECURED • RESUME SCAVENGING"}
function flash(t){const s=$("#combatStatus");if(!s)return;const old=s.style.boxShadow;s.style.boxShadow="0 0 18px #ff4f61";setTimeout(()=>s.style.boxShadow=old,280);log(t)}
function log(t){const f=$("#gameFeed");if(f){const d=document.createElement("div");d.className="feed-item";d.textContent=t;f.prepend(d)}}
function panel(){const hud=$(".hud");if(!hud||$("#combatTelemetry"))return;const c=document.createElement("section");c.id="combatTelemetry";c.className="hud-card combat-telemetry";c.innerHTML='<div class="hud-label">COMBAT TELEMETRY</div><div class="combat-stats"><span>WEAPON DAMAGE <b id="weaponDamage"></b></span><span>ATTACK SPEED <b id="attackSpeed"></b></span><span>ARMOR MITIGATION <b id="armorValue"></b></span></div>';const anchor=$(".inventory-launch");hud.insertBefore(c,anchor||null);const w=getWeapon();$("#weaponDamage").textContent=w.damage;$("#attackSpeed").textContent=(1000/w.cooldown).toFixed(1)+"/s";$("#armorValue").textContent=Math.round(armor()*100)+"%"}
function init(){ensure();panel();render();$("#attackBtn")?.addEventListener("click",combat);document.addEventListener("keydown",e=>{if(e.code==="Space"){e.preventDefault();combat()}})}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init()})();