(()=>{"use strict";const $=s=>document.querySelector(s);
const TABLE={common:["🥫 Canned Food","💧 Water Bottle","🩹 Bandage","🔦 Flashlight"],uncommon:["💊 Painkillers","🧰 Repair Kit","🔋 Power Cell","🔧 Crowbar"],rare:["💉 Medical Kit","📡 Emergency Beacon","🪓 Rescue Axe"],epic:["🩸 Trauma Kit","🗝️ Master Keycard"]};
const CONTAINERS=[{type:"CIVILIAN CACHE",icon:"📦",tier:"common",chance:.72,locked:false},{type:"MEDICAL CABINET",icon:"🗄️",tier:"uncommon",chance:.62,locked:false},{type:"POLICE LOCKER",icon:"🔐",tier:"rare",chance:.48,locked:true},{type:"EMERGENCY CRATE",icon:"🧳",tier:"rare",chance:.54,locked:false},{type:"SECURE CASE",icon:"🔒",tier:"epic",chance:.35,locked:true}];
const state={containers:[],selected:null};
function rand(a){return a[Math.floor(Math.random()*a.length)]}function rarity(){const r=Math.random();return r<.03?"epic":r<.14?"rare":r<.42?"uncommon":"common"}function make(){return CONTAINERS.map((c,i)=>({...c,id:"container-"+i+"-"+Math.random().toString(36).slice(2,6),opened:false,locked:c.locked,rarity:c.tier})).sort(()=>Math.random()-.5).slice(0,3+Math.floor(Math.random()*3))}
function ensure(){try{const saved=JSON.parse(localStorage.getItem("outbreak_containers")||"null");state.containers=Array.isArray(saved)&&saved.length?saved:make()}catch{state.containers=make()}save()}
function save(){localStorage.setItem("outbreak_containers",JSON.stringify(state.containers))}
function render(){const host=document.querySelector(".game-actions");if(!host||$("#containersBtn"))return;const b=document.createElement("button");b.id="containersBtn";b.className="game-btn loot";b.textContent="▣ SEARCH CONTAINERS";host.insertBefore(b,host.firstChild);b.onclick=openList}
function openList(){const m=modal();const available=state.containers.filter(c=>!c.opened);$("#containerResults").innerHTML=available.length?available.map(c=>'<button class="container-row '+c.rarity+'" data-container="'+c.id+'"><span>'+c.icon+'</span><div><b>'+c.type+'</b><small>'+c.rarity.toUpperCase()+' // '+(c.locked?"LOCKED":"ACCESSIBLE")+'</small></div><em>SEARCH →</em></button>').join(""):'<div class="container-empty"><b>ALL NEARBY CONTAINERS SEARCHED</b><small>Move to another area to locate new caches.</small></div>';m.classList.remove("hidden");document.querySelectorAll("[data-container]").forEach(b=>b.onclick=()=>inspect(b.dataset.container))}
function inspect(id){const c=state.containers.find(x=>x.id===id);if(!c)return;state.selected=c;const m=modal();const lock=c.locked?'<div class="lock-status">🔒 LOCKED CONTAINER — REQUIRES KEYCARD OR FORCED ENTRY</div>':'';$("#containerResults").innerHTML='<div class="container-inspect"><div class="container-big-icon">'+c.icon+'</div><span class="rarity-tag '+c.rarity+'">'+c.rarity.toUpperCase()+'</span><h3>'+c.type+'</h3>'+lock+'<p>Search quality and container type influence recovered assets.</p><div class="modal-actions"><button id="containerBack">BACK</button><button id="containerSearch">'+(c.locked?"ATTEMPT ACCESS":"SEARCH CONTAINER")+'</button></div></div>';$("#containerBack").onclick=openList;$("#containerSearch").onclick=()=>search(c)}
function search(c){const inv=(()=>{try{return JSON.parse(localStorage.getItem("outbreak_inventory")||"[]")}catch{return[]}})();const hasKey=inv.some(x=>/keycard/i.test(x));if(c.locked&&!hasKey&&Math.random()>.35){$("#containerResults").innerHTML='<div class="container-empty"><b>ACCESS DENIED</b><small>The lock holds. Find a keycard or return better prepared.</small><button id="containerBack" class="game-btn">RETURN</button></div>';$("#containerBack").onclick=openList;return}const count=c.rarity==="epic"?2+Math.floor(Math.random()*2):1+Math.floor(Math.random()*2);const found=[];for(let i=0;i<count;i++){let tier=c.rarity;if(Math.random()<.28)tier=rarity();found.push(rand(TABLE[tier]))}c.opened=true;c.locked=false;save();const room=Math.max(0,Number(localStorage.getItem("outbreak_inventory_capacity")||8)-inv.length),taken=found.slice(0,room);localStorage.setItem("outbreak_inventory",JSON.stringify([...inv,...taken]));$("#containerResults").innerHTML='<div class="container-loot"><span class="modal-kicker">CONTAINER SECURED</span><h3>'+c.type+'</h3><div class="loot-results">'+found.map((x,i)=>'<div class="loot-found '+(i>=room?"blocked":"")+'">'+x+'<small>'+ (i>=room?"NO SPACE":"TAKEN")+'</small></div>').join("")+'</div><div class="modal-actions"><button id="containerDone">CONTINUE RAID</button></div></div>';$("#containerDone").onclick=()=>{$("#containerModal").classList.add("hidden");updateInventory();log("Container searched: "+c.type+" • "+taken.length+" item(s) secured")}}
function updateInventory(){const inv=(()=>{try{return JSON.parse(localStorage.getItem("outbreak_inventory")||"[]")}catch{return[]}})(),cap=localStorage.getItem("outbreak_inventory_capacity")||8;const n=$("#inventoryCount");if(n)n.textContent=inv.length+" / "+cap}
function log(t){const f=$("#gameFeed");if(f){const d=document.createElement("div");d.className="feed-item";d.textContent=t;f.prepend(d)}}
function modal(){let m=$("#containerModal");if(!m){m=document.createElement("div");m.id="containerModal";m.className="modal hidden";m.innerHTML='<div class="modal-card container-modal"><span class="modal-kicker">PHASE 6A // LOOT DISCOVERY</span><h2>NEARBY CONTAINERS</h2><div id="containerResults" class="container-results"></div><div class="modal-actions"><button id="containerClose">CLOSE</button></div></div>';document.body.appendChild(m);$("#containerClose").onclick=()=>m.classList.add("hidden")}return m}
function init(){ensure();render();updateInventory();document.addEventListener("keydown",e=>{if(e.key.toLowerCase()==="l"&&!e.repeat)openList()})}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init()})();