(()=>{"use strict";const $=s=>document.querySelector(s);
const LEVELS=[{name:"QUIET",min:0,max:19,desc:"Minimal infected activity."},{name:"ALERT",min:20,max:44,desc:"Movement detected nearby."},{name:"ESCALATING",min:45,max:69,desc:"Reinforcements converging."},{name:"DANGER",min:70,max:89,desc:"Horde pressure rising."},{name:"HORDE",min:90,max:100,desc:"Overwhelming infected presence."}];
let state={noise:0,pressure:18,night:false,horde:false,last:Date.now()},timer;
function load(){try{return {...state,...JSON.parse(localStorage.getItem("outbreak_threat_state")||"{}")}}catch{return state}}
function save(){localStorage.setItem("outbreak_threat_state",JSON.stringify(state))}
function level(){return LEVELS.find(x=>state.pressure>=x.min&&state.pressure<=x.max)||LEVELS[0]}
function render(){const l=level(),t=$("#threat");if(t)t.textContent="THREAT: "+l.name;const meter=$("#threatMeter"),noise=$("#noiseValue"),pressure=$("#pressureValue"),phase=$("#worldPhase");if(meter)meter.style.width=state.pressure+"%";if(noise)noise.textContent=Math.round(state.noise)+"%";if(pressure)pressure.textContent=Math.round(state.pressure)+"%";if(phase)phase.textContent=state.night?"NIGHT OPERATIONS":"DAY OPERATIONS";const card=$("#threatTelemetry");if(card)card.dataset.level=l.name.toLowerCase()}
function log(x){const f=$("#gameFeed");if(f){const d=document.createElement("div");d.className="feed-item";d.textContent=x;f.prepend(d)}}
function add(amount,reason){state.noise=Math.min(100,state.noise+amount);state.pressure=Math.min(100,state.pressure+amount*.75);if(reason)log("⚠ "+reason+" • THREAT +"+Math.round(amount*.75));check();save();render()}
function decay(){state.noise=Math.max(0,state.noise-3);state.pressure=Math.max(8,state.pressure-1.2+(state.night?.7:0));check();save();render()}
function check(){if(state.pressure>=90&&!state.horde){state.horde=true;spawnHorde()}else if(state.pressure<65)state.horde=false}
function spawnHorde(){log("☣☣☣ HORDE EVENT • MULTIPLE INFECTED CONVERGING");document.dispatchEvent(new CustomEvent("cheegunHorde",{detail:{pressure:state.pressure}}));const modal=document.createElement("div");modal.className="modal";modal.id="hordeAlert";modal.innerHTML='<div class="modal-card horde-alert"><span class="modal-kicker">EMERGENCY THREAT ALERT</span><h2>☣ HORDE INBOUND</h2><p>Noise and activity have triggered a large infected convergence. Break contact or prepare to defend.</p><div class="modal-actions"><button id="hordeAcknowledge">ACKNOWLEDGE</button></div></div>';document.body.appendChild(modal);$("#hordeAcknowledge").onclick=()=>modal.remove()}
function panel(){const hud=$(".hud");if(!hud||$("#threatTelemetry"))return;const c=document.createElement("section");c.id="threatTelemetry";c.className="hud-card threat-telemetry";c.innerHTML='<div class="hud-label">OUTBREAK THREAT NETWORK <span id="worldPhase"></span></div><div class="threat-readout"><span>NOISE <b id="noiseValue">0%</b></span><span>PRESSURE <b id="pressureValue">0%</b></span></div><div class="threat-bar"><i><b id="threatMeter"></b></i></div><small>GUNFIRE • COMBAT • HIGH-RISK ZONES INCREASE PRESSURE</small>';hud.insertBefore(c,$(".feed-card")||null)}
function clock(){const time=$("#gameTime");if(!time)return;const h=Number((time.textContent||"08:00").slice(0,2));state.night=h>=19||h<6}
function hook(){document.addEventListener("cheegunWeaponNoise",e=>add(e.detail?.amount||8,"WEAPON NOISE"));document.addEventListener("cheegunInfectedStrike",()=>add(5,"COMBAT CONTACT"));document.addEventListener("cheegunHorde",()=>{});document.addEventListener("click",e=>{if(e.target.closest("#zonesBtn"))add(7,"HIGH-VALUE ZONE MOVEMENT");if(e.target.closest("#scavengeBtn"))add(3,"SCAVENGING ACTIVITY")})}
function init(){state=load();clock();panel();hook();render();timer=setInterval(()=>{clock();decay()},8000);log("THREAT NETWORK ACTIVE • WORLD REACTS TO OPERATOR ACTIVITY")}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init()})();